[package]
name = "{{ project_name}}_graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
{{ project_name }}_core = { path = "../{{ project_name }}_core" }

async-graphql = "7.0.3"